pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Deploy spring boot aplicatio') {
      agent {
        docker { image '12345199354321/pet-clinic123' }
      }
      steps {
        sh 'docker run -d -p 9000:8082 12345199354321/pet-clinic123'
      }
    }
  }
}
